version: "3.8"
services:
  lgpt:
    build:
      context: ./localGPT_docker
      dockerfile: Dockerfile
      args:
        GPT_LISTENING_IP: ${GPT_LISTENING_IP}
        GPT_INTERNAL_PORT: ${GPT_INTERNAL_PORT}
    command: /bin/sh -c "cp constitution.pdf /SOURCE_DOCUMENTS && python run_localGPT_API.py"
    image: local_gpt:latest
    container_name: local_gpt
    restart: unless-stopped
    networks:
      - lgpt_net
    ports:
      - "${GPT_EXTERNAL_PORT}:${GPT_INTERNAL_PORT}"
  lgpt_app:
    build:
      context: ./lgpt-t3-app
      dockerfile: Dockerfile
      args:
        APP_INTERNAL_PORT: ${APP_INTERNAL_PORT}
    image: lgpt_app:latest
    depends_on:
      - lgpt
    container_name: lgpt_app
    restart: unless-stopped 
    ports: 
      - "${APP_EXTERNAL_PORT}:${APP_INTERNAL_PORT}"
    networks:
      - lgpt_net
networks:
  lgpt_net:
    name: lgpt_net
